WeBankFinTech/fes.js

packages/fes-preset-built-in/src/utils/generateFiles.js
=> fix: 修复 watch 池为空

packages/fes-plugin-request/src/template/genRequestKey.js, packages/fes-template-h5/src/pages/index.vue
解决 get 请求生成  URL key 时，忽略 params 参数问题。
=> Fix request key

packages/fes-plugin-enums/src/runtime/core.tpl
=> 更新plugin-enums中get放大发JSDoc，后两个参数为可选

packages/fes-plugin-request/src/template/resDataAdaptor.js, packages/fes-template-h5/src/pages/index.vue
=> Perf request

packages/create-fes-app/templates/app/pc/package.json, packages/fes-plugin-layout/package.json, packages/fes-plugin-layout/src/runtime/views/BaseLayout.vue, packages/fes-template/.fes.js, packages/fes-template/package.json, packages/fes-template/src/pages/index.vue, packages/fes-template/src/pages/menuTest/@id.vue, packages/fes-template/src/pages/menuTest/index.vue, packages/fes-template/src/pages/menuTest/layout.vue, yarn.lock
1. top:auto在低版本上有兼容问题，去掉
2. 优化一些写法
3. 升级fes-design版本
=> refactor: layout组件兼容性更好,升级fes-design版本

docs/reference/plugin/plugins/watermark.md, packages/fes-plugin-watermark/src/index.js, packages/fes-plugin-watermark/src/runtime/core.js
=> Feat watermark close

scripts/build.mjs, scripts/compiler.mjs
node scripts/build.mjs --watch 的时候输出一个inlinde的sourcemap 
这样vscode的debugger就能正确的连上去了。
=> feat(build script): generate sourcemap for developer

packages/fes-plugin-layout/src/runtime/views/BaseLayout.vue, packages/fes-plugin-layout/src/runtime/views/Menu.vue, yarn.lock
close https://github.com/WeBankFinTech/fes.js/issues/170
=> fix: layout插件菜单会自动展开当前路由 & 修复之前不合理用法

docs/guide/route.md, packages/fes-preset-built-in/src/plugins/misc/route/index.js, packages/fes-template/src/pages/[...].vue
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix: 添加[...slug].vue方式替换*.vue实现模糊匹配

packages/fes-plugin-access/src/runtime/core.tpl, packages/fes-plugin-layout/src/runtime/helpers/pluginAccess.js, packages/fes-plugin-layout/src/runtime/helpers/pluginLocale.js, packages/fes-plugin-layout/src/runtime/runtime.js, packages/fes-plugin-layout/src/runtime/views/Menu.vue, packages/fes-plugin-locale/src/runtime/core.tpl, packages/fes-plugin-locale/src/runtime/runtime.js
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix: 修复layout菜单折叠不更新状态问题

packages/fes-plugin-swc/package.json, pnpm-lock.yaml
=> chore: upgrade swc-plugin-vue-jsx

packages/fes-plugin-layout/src/runtime/runtime.js, packages/fes-preset-built-in/src/plugins/core/route/index.js
-   [ ] Bugfix
-   [x] Docs
-   [ ] Yes
-   [x] No
=> fix: 完善路由文件命名提示 & 保证403和404路由一直有权限

docs/reference/plugin/plugins/layout.md, packages/fes-plugin-layout/src/runtime/views/BaseLayout.vue, packages/fes-template/src/app.js
=> feat: logo 添加点击事件

docs/.vitepress/config.ts, docs/.vitepress/configs/navbar/zh.ts, docs/reference/config/index.md, package.json, packages/fes-plugin-jest/package.json, packages/fes-preset-built-in/src/plugins/features/globalCSS.js, packages/fes-preset-built-in/types.d.ts, pnpm-lock.yaml
=> feat: 增加配置控制全局样式加载顺序

packages/fes-builder-webpack/src/plugins/commands/dev/devServer.js
=> fix: 删去 webpack dev overlay 全屏弹窗

packages/fes-plugin-request/src/template/request.js
=> fix: 修复 request 初始化问题

packages/fes-builder-webpack/package.json, pnpm-lock.yaml
=> Fix upgrade webpack

packages/fes-builder-vite/src/common/getConfig.js, packages/fes-builder-vite/src/index.js, packages/fes-builder-webpack/package.json, packages/fes-template-vite/.fes.js, pnpm-lock.yaml
-   [x] Bugfix
-   [x] No
close #196
=> fix: 修复 vite html 配置问题

packages/fes-plugin-layout/src/runtime/views/BaseLayout.vue, packages/fes-template/.fes.js
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
https://github.com/WeBankFinTech/fes.js/issues/201
=> fix: 修复plugin-layout中body的top计算问题

packages/fes-plugin-access/types.d.ts
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix(plugin-access): 修复 useAccess 类型定义

docs/reference/plugin/plugins/locale.md, packages/fes-plugin-locale/package.json, packages/fes-plugin-locale/src/index.js, packages/fes-plugin-locale/src/runtime/core.js.tpl, packages/fes-plugin-locale/src/runtime/locales.js.tpl, packages/fes-plugin-locale/src/utils/index.js, packages/fes-template/src/locales/en-US.js, packages/fes-template/src/locales/home/en-US.js, packages/fes-template/src/locales/home/zh-CN.js, packages/fes-template/src/locales/zh-CN.js
-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
#213 
=> feat: 国际化支持模块化配置

package.json, packages/create-fes-app/templates/app/pc/package.json, packages/fes-plugin-layout/package.json, packages/fes-plugin-locale/package.json, packages/fes-plugin-qiankun/examples/app1/package.json, packages/fes-plugin-qiankun/examples/main/package.json, packages/fes-plugin-qiankun/package.json, packages/fes-template/package.json, yarn.lock
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> Fix versions

docs/reference/plugin/plugins/request.md
=> docs: 优化 request 文档

.eslintrc.js, packages/fes-builder-vite/package.json, packages/fes-builder-vite/src/common/connectHistoryMiddleware.js, packages/fes-builder-vite/src/common/getConfig.js, packages/fes-builder-vite/src/common/vite-plugin-html.js, pnpm-lock.yaml
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix: 修复vite构建时public下的html文件无法正常访问问题

packages/fes-plugin-request/src/template/request.js
=> fix: 优化 rawRequest

packages/fes-builder-webpack/src/plugins/common/webpackConfig/index.js
=> fix: webpack 丢失 publicPath

packages/fes-plugin-layout/src/runtime/views/components/Wrapper.vue
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix(plugin-layout): 403、404 样式优化，防止被覆盖

packages/fes-plugin-locale/src/utils/index.js
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix(plugin-locale): 修复 win 环境处理文件路径问题

packages/fes-plugin-request/package.json, packages/fes-plugin-request/src/index.js, packages/fes-plugin-request/src/template/request.js
=> fix: 解决 reqeust 生成文件流的问题

packages/fes-plugin-access/src/runtime/core.tpl, packages/fes-plugin-layout/src/runtime/runtime.js.tpl
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix(plugin-access): 修复切换角色时，getAccess 不正确

packages/fes-plugin-login/src/runtime/runtime.js, packages/fes-plugin-request/package.json, pnpm-lock.yaml
=> fix: login 兼容不同的 request 版本

packages/fes-plugin-layout/src/runtime/views/BaseLayout.vue, packages/fes-plugin-layout/types.d.ts
-   [ ] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> feat(plugin-layout): 增加 top-left 布局类型

packages/fes-utils/src/getHostName.js
=> refactor: 优化 dev server ip监听

packages/fes-plugin-layout/src/index.js
=> fix: fes layout 添加 route name, 用于动态路由创建

packages/fes-plugin-qiankun/src/micro/runtime/qiankunModel.tpl
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix: 修复清空父应用状态,子应用状态未清空问题

packages/fes-plugin-access/src/runtime/createDirective.js
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [x] No
=> fix: v-access指令无法控制元素展示隐藏

packages/fes-plugin-layout/package.json, packages/fes-plugin-layout/src/runtime/helpers/svg.js, packages/fes-plugin-layout/src/runtime/views/MenuIcon.vue, packages/fes-template/src/app.jsx, pnpm-lock.yaml
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No
=> feat: 修复xss漏洞

.eslintignore, eslint.config.js, package.json, packages/fes-builder-webpack/package.json, packages/fes-compiler/package.json, packages/fes-compiler/src/config/utils/configUtils.js, packages/fes-preset-built-in/package.json, packages/fes-preset-built-in/src/plugins/features/mock.js, packages/fes-template/tsconfig.json, pnpm-lock.yaml, tsconfig.base.json
=> chore: 修复安全告警问题

docs/reference/plugin/plugins/layout.md, packages/fes-plugin-layout/src/runtime/views/MultiTabProvider.vue
=> fix: 控制 tab 是否可以刷新

docs/guide/upgrade3.md, packages/fes-builder-webpack/package.json, packages/fes-builder-webpack/src/plugins/commands/dev/connectHistoryMiddleware.js, packages/fes-builder-webpack/src/plugins/commands/dev/devServer.js, packages/fes-builder-webpack/src/plugins/commands/dev/index.js, packages/fes-builder-webpack/src/plugins/common/webpackConfig/index.js, pnpm-lock.yaml
=> feat: webpack-dev 升级到5.x,提升 dev 性能,优化日志输出

packages/create-fes-app/templates/app/pc/package.json
-   [x] Bugfix
-   [ ] Docs
-   [ ] Yes
-   [ ] No
=> fix: 修复pc模版无法启动问题

packages/fes-builder-webpack/src/plugins/commands/dev/connectHistoryMiddleware.js
=> fix: 代理插件兼容 array 写法

docs/reference/config/index.md, packages/fes-preset-built-in/src/index.js, packages/fes-preset-built-in/src/plugins/core/entry/fes.tpl, packages/fes-preset-built-in/src/plugins/core/entry/index.js, packages/fes-preset-built-in/src/plugins/features/console.js, packages/fes-preset-built-in/types.d.ts, packages/fes-template/.fes.js
=> feat: 添加 console 配置,支持输出 version
